name: CosmoPocket Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'   # UTC 01:00 = 北京 09:00

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN:   ${{ secrets.SLACK_BOT_TOKEN }}   # ← 名字对齐代码
      CHANNEL_BUFFER_ID: ${{ secrets.CHANNEL_BUFFER_ID }}
      CHANNEL_BRIDGE_ID: ${{ secrets.CHANNEL_BRIDGE_ID }} # 可选
      CI: "true"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # 可选：探针，确认变量已注入（只看长度/前缀，避免泄露）
      - name: Sanity check env (masked)
        run: |
          node -e "console.log('TOK_LEN', (process.env.SLACK_BOT_TOKEN||'').length)"
          node -e "console.log('BUF_ID', (process.env.CHANNEL_BUFFER_ID||'').slice(0,2))"

      - run: npm ci
      - run: node test-auth.js
      - run: node digest.js
