name: Daily Digest

on:
  schedule:
    # UTC 01:00 ≈ 北京时间 09:00
    - cron: '0 1 * * *'
  workflow_dispatch: {}

env:
  TZ: Asia/Shanghai

jobs:
  digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: sinan-relay/package-lock.json

      - name: Install deps
        working-directory: sinan-relay
        run: npm ci

      # 任选其一：A 或 B
      # A) step 级 if（表达式要用 ${{ }} 包裹）
      # - name: Export HTTPS proxy (optional)
      #   if: ${{ secrets.HTTPS_PROXY != '' }}
      #   run: echo "HTTPS_PROXY=${{ secrets.HTTPS_PROXY }}" >> $GITHUB_ENV

      # B) 用 bash 判断（推荐，更稳）
      - name: Export HTTPS proxy (optional)
        run: |
          if [ -n "${{ secrets.HTTPS_PROXY }}" ]; then
            echo "HTTPS_PROXY=${{ secrets.HTTPS_PROXY }}" >> $GITHUB_ENV
            echo "Set HTTPS_PROXY"
          else
            echo "HTTPS_PROXY not set, skip."
          fi

      - name: Run digest
        working-directory: sinan-relay
        env:
          SLACK_BOT_TOKEN:    ${{ secrets.SLACK_BOT_TOKEN }}
          OPENAI_API_KEY:     ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL:       gpt-4o-mini
          DIGEST_HOURS:       24
          CHANNEL_BRIDGE_ID:  ${{ secrets.CHANNEL_BRIDGE_ID }}
          CHANNEL_BUFFER_ID:  ${{ secrets.CHANNEL_BUFFER_ID }}
          HTTPS_PROXY:        ${{ secrets.HTTPS_PROXY }}
        run: npm run digest
